### ISSUE TITLE
Close off canvas using ESC

### ISSUE THREAD

**Issue by jquimera** [onokumus/onoffcanvas#3]
it would be possible close the off-canvas using ESC keyboard.?

**Comment by onokumus** [comment]
@jquimera 
Currently, this feature is not available.

**Comment by jquimera** [comment]
@onokumus May also have some callbacks. Like this: https://github.com/vmitsaras/js-offcanvas#options

**Comment by onokumus** [comment]
@jquimera 
https://github.com/onokumus/onoffcanvas#hidebyesc
